#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

env_nl_scene_builder = env.Clone()
env_nl_scene_builder.Prepend(CPPPATH=["#editor/plugins/nl_scene_builder"])
env_nl_scene_builder.add_source_files(env.editor_sources, "*.cpp")

